### ISSUE TITLE
Port to snickerdoodle black

### ISSUE THREAD

**Issue by toastedcrumpets** [peabody124/snickerdoodle-pynq#1]
Hi
I noticed you're attempting a port to snickerdoodle black. I have one of these boards and I'm looking to do the same. Do you want help with testing/porting? I'm new to zynq but have used spartan/linux heavily before.

**Comment by peabody124** [comment]
@toastedcrumpets it is working now on black with at least ethernet. closing this issue.

**Comment by toastedcrumpets** [comment]
Thanks! Will try it out
