### ISSUE TITLE
Enable Ethernet

### ISSUE THREAD

**Issue by peabody124** [peabody124/snickerdoodle-pynq#2]
Trying to get the ethernet for PiSmasher working. It is getting close, to the point that u-boot detects it:

```
Net:   ZYNQ GEM: e000b000, phyaddr 0, interface rgmii-id
eth0: ethernet@e000b000
U-BOOT for xilinx-snickerdoodleblack-2018.3

ethernet@e000b000 Waiting for PHY auto negotiation to complete.... done
BOOTP broadcast 1
BOOTP broadcast 2
BOOTP broadcast 3
BOOTP broadcast 4
BOOTP broadcast 5
BOOTP broadcast 6
```

But both u-boot and linux never get an IP address. There are two telling hints at the issue. During boot in linux I see:
```
[    1.092717] libphy: Fixed MDIO Bus: probed
[    1.098992] libphy: MACB_mii_bus: probed
[    1.103410] xgmiitorgmii e000b000.ethernet-ffffffff:08: External PHY driver not probed
[    1.111668] macb e000b000.ethernet eth0: Cadence GEM rev 0x00020118 at 0xe000b000 irq 29 (00:0a:35:00:1e:53)
[    1.121804] Generic PHY e000b000.ethernet-ffffffff:00: attached PHY driver [Generic PHY] (mii_bus:phy_addr=e000b000.ethernet-ffffffff:00, irq=POLL)
[    1.135297] e1000e: Intel(R) PRO/1000 Network Driver - 3.2.6-k
```
also possibly relevant, if there Marvel PHY driver is enabled that is what grabs it. Only by disabling do I get generic, but on the official builds both are modules and generic gets hooked.

I don't see the linux message about External PHY driver not probed on the krtkl official build. Additionally, when bringing the link up then down again:
```
[   52.349209] macb e000b000.ethernet eth0: link down
[   54.242232] macb e000b000.ethernet eth0: unable to generate target frequency: 25000000 Hz
[   54.242247] macb e000b000.ethernet eth0: link up (100/Full)
```

Now I actually see a similar message about clock frequency on the official builds but it is using gigabit and sets a higher target frequency:
```
[   54.790703] macb e000b000.ethernet eth0: link down
[   57.827903] macb e000b000.ethernet eth0: unable to generate target frequency: 125000000 Hz
[   57.827921] macb e000b000.ethernet eth0: link up (1000/Full)
```

All of this is on c70dc4d120591992b86e71658acae20b1929b4fc

**Comment by peabody124** [comment]
Working!

**Comment by junhyoung91** [comment]
How did you solve it?
